SEED: 0

model_cfgs:
  model_name: unet
  model_args:
    encoder_name: mobilenetv3
    in_channel_nb: 3
    classes_nb: 3

dataset_cfgs:
  name: BioSeg_RGB_datasets
  data_dir: F:\Data\bio_colonization
  collection: nir
  classes:
    - background
    - bio_green
    - bio_dark

loss_cfgs:
  loss_name: ce
  loss_args:
    alpha: 0.75         # used by focal, focal_multi, combo
    gamma: 2.0         # used by focal, focal_multi
    reduction: mean    # used by ce, bce, focal, focal_multi
    weight: ~          # used by ce, bce
    smooth: 1e-6        # used by dice

train_cfgs:
  optimizer: adam               # 可选项：adam / adamw / sgd
  lr_rate: 0.001
  lr_scheduler: step             # 可选项：step / multistep / cosine
  lr_scheduler_step: 10
  lr_scheduler_gamma: 0.1
  lr_scheduler_milestones: [ 30, 60 ]  # 如果用 multistep
  lr_scheduler_tmax: 50              # 如果用 cosine
  batch_size: 4
  epochs: 50
  save_cm_interval: 4
  early_stopping:
    enabled: True        # 是否启用 EarlyStopping
    monitor: val_loss    # 监控的指标
    patience: 10         # 容忍轮数
    mode: min            # 优化方向（min 或 max）

plot_cfgs:
  save_last_epoch_result: True
  plot_classification_curve: False
  max_points: 1000000  # 最多保存的像素点数