model_cfgs:
  model_name: unet
  model_args:
    encoder_name: mobilenetv3
    in_channel_nb: 25
    classes_nb: 2

dataset_cfgs:
  data_dir: F:\Data\hsi_road\hsi_road
  collection: nir
  classes:
    - background
    - road

loss_cfgs:
  loss_name: ce
  loss_args:
    alpha: 0.75         # used by focal, focal_multi, combo
    gamma: 2.0         # used by focal, focal_multi
    reduction: mean    # used by ce, bce, focal, focal_multi
    weight: ~          # used by ce, bce
    smooth: 1e-6        # used by dice

train_cfgs:
  lr_rate: 0.01
  lr_scheduler_step: 10
  lr_scheduler_gamma: 0.1
  batch_size: 8
  epochs: 10
